#!/usr/bin/env node
/**
 * Bundle the arena server (sandbox/dev-server.ts -> index.ts: passports +
 * gateway + arena WSS) into ONE file for the runtime image:
 *
 *   node sandbox/build-server.mjs [--outdir <dir>]      (default: sandbox/dist)
 *
 * Writes:
 *   <outdir>/arena-server.mjs                   ESM, platform node, target node22
 *   <outdir>/THIRD_PARTY_LICENSES.server.txt    licence text of every npm
 *                                               package that ends up in the bundle
 *
 * Why a separate bundle from `build:cli` (packages/arena-cli, B1): the CLI is
 * the npm/SEA product and must not carry express or the passports plane; the
 * arena server is only ever run from the image. Both bundles ship in the same
 * image and run on the same Node binary.
 *
 * `esbuild` comes from the lockfile (today via `tsx`; B1 adds it as a direct
 * devDependency for `build:cli`). No network, no install scripts.
 *
 * The open core ships no hosted identity SDK (ADR-003 §3, EXTRACTION §10):
 * Architect tokens are verified by `jose` against a configured JWKS
 * (agent-passports §1.1), which is bundled like any other dependency. With no
 * JWKS configured the register and webhook gates fail closed (401) unless the
 * local WOT_DEV_AUTH=1 bypass is on, which is the intended sandbox behaviour.
 * `bufferutil`/`utf-8-validate` are optional `ws` natives, left EXTERNAL.
 */

import { build } from 'esbuild';
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');

const argOut = process.argv.indexOf('--outdir');
const outdir = resolve(argOut > 0 ? process.argv[argOut + 1] : join(HERE, 'dist'));
mkdirSync(outdir, { recursive: true });

const EXTERNAL = ['bufferutil', 'utf-8-validate'];

const result = await build({
  entryPoints: [join(HERE, 'dev-server.ts')],
  outfile: join(outdir, 'arena-server.mjs'),
  bundle: true,
  platform: 'node',
  target: 'node22',
  format: 'esm',
  external: EXTERNAL,
  // CJS dependencies (express, ws) call require() on node builtins; give the
  // ESM bundle a real require.
  banner: {
    js: "import { createRequire as __arenaCreateRequire } from 'node:module'; const require = __arenaCreateRequire(import.meta.url);",
  },
  legalComments: 'none',
  sourcemap: false,
  minify: false,
  metafile: true,
  logLevel: 'warning',
  absWorkingDir: ROOT,
});

// ---- third-party licences for the bundled packages ----
const pkgDirs = new Set();
for (const input of Object.keys(result.metafile.inputs)) {
  const m = input.match(/^(.*node_modules\/(?:@[^/]+\/)?[^/]+)\//);
  if (m) pkgDirs.add(m[1]);
}
const sections = [];
for (const rel of [...pkgDirs].sort()) {
  const dir = join(ROOT, rel);
  const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'));
  const licFile = readdirSync(dir).find((f) => /^(licen[cs]e|copying)(\.|$)/i.test(f));
  const text = licFile ? readFileSync(join(dir, licFile), 'utf8').trim() : `(no licence file shipped; package.json declares: ${pkg.license ?? 'UNKNOWN'})`;
  sections.push(`${pkg.name}@${pkg.version} (${pkg.license ?? 'UNKNOWN'})\n${'-'.repeat(72)}\n${text}\n`);
}
const header =
  'Third-party software bundled into arena-server.mjs (the arena server of the\n' +
  'agent-arena sandbox image). Generated by sandbox/build-server.mjs from the\n' +
  'esbuild metafile.\n\n';
writeFileSync(join(outdir, 'THIRD_PARTY_LICENSES.server.txt'), header + sections.join('\n'));

if (!existsSync(join(outdir, 'arena-server.mjs'))) throw new Error('bundle not written');
process.stdout.write(`arena-server.mjs + THIRD_PARTY_LICENSES.server.txt (${pkgDirs.size} packages) -> ${outdir}\n`);
