/**
 * Standard Diplomacy map — DATA ONLY (docs/design/diplomacy-adjudicator.md §1.2).
 *
 * Hand-entered from the published standard board. NOT derived from, copied from,
 * or checked against any Diplomacy engine's map or adjacency files (clean-room,
 * ADR-002; see ./README.md). Any edit changes MAP_DIGEST and fails the pinned
 * digest test in test/diplomacy-map.test.ts on purpose.
 *
 * Authoring: each province's neighbour list was entered from the board from BOTH
 * ends; a symmetry check then produced these undirected lists (each pair once,
 * a < b in ASCII order, sorted).
 */

import type { NodeId, ProvinceDef, ProvinceId } from './types.ts';

/** 75 provinces sorted by id (19 sea, 14 inland, 42 coastal; 34 SCs, 22 home). */
export const PROVINCES: readonly ProvinceDef[] = [
  { id: 'adr', name: 'Adriatic Sea', kind: 'sea', sc: false, home: null, coasts: [] },
  { id: 'aeg', name: 'Aegean Sea', kind: 'sea', sc: false, home: null, coasts: [] },
  { id: 'alb', name: 'Albania', kind: 'coastal', sc: false, home: null, coasts: [] },
  { id: 'ank', name: 'Ankara', kind: 'coastal', sc: true, home: 'turkey', coasts: [] },
  { id: 'apu', name: 'Apulia', kind: 'coastal', sc: false, home: null, coasts: [] },
  { id: 'arm', name: 'Armenia', kind: 'coastal', sc: false, home: null, coasts: [] },
  { id: 'bal', name: 'Baltic Sea', kind: 'sea', sc: false, home: null, coasts: [] },
  { id: 'bar', name: 'Barents Sea', kind: 'sea', sc: false, home: null, coasts: [] },
  { id: 'bel', name: 'Belgium', kind: 'coastal', sc: true, home: null, coasts: [] },
  { id: 'ber', name: 'Berlin', kind: 'coastal', sc: true, home: 'germany', coasts: [] },
  { id: 'bla', name: 'Black Sea', kind: 'sea', sc: false, home: null, coasts: [] },
  { id: 'boh', name: 'Bohemia', kind: 'inland', sc: false, home: null, coasts: [] },
  { id: 'bot', name: 'Gulf of Bothnia', kind: 'sea', sc: false, home: null, coasts: [] },
  { id: 'bre', name: 'Brest', kind: 'coastal', sc: true, home: 'france', coasts: [] },
  { id: 'bud', name: 'Budapest', kind: 'inland', sc: true, home: 'austria', coasts: [] },
  { id: 'bul', name: 'Bulgaria', kind: 'coastal', sc: true, home: null, coasts: ['ec', 'sc'] },
  { id: 'bur', name: 'Burgundy', kind: 'inland', sc: false, home: null, coasts: [] },
  { id: 'cly', name: 'Clyde', kind: 'coastal', sc: false, home: null, coasts: [] },
  { id: 'con', name: 'Constantinople', kind: 'coastal', sc: true, home: 'turkey', coasts: [] },
  { id: 'den', name: 'Denmark', kind: 'coastal', sc: true, home: null, coasts: [] },
  { id: 'eas', name: 'Eastern Mediterranean', kind: 'sea', sc: false, home: null, coasts: [] },
  { id: 'edi', name: 'Edinburgh', kind: 'coastal', sc: true, home: 'england', coasts: [] },
  { id: 'eng', name: 'English Channel', kind: 'sea', sc: false, home: null, coasts: [] },
  { id: 'fin', name: 'Finland', kind: 'coastal', sc: false, home: null, coasts: [] },
  { id: 'gal', name: 'Galicia', kind: 'inland', sc: false, home: null, coasts: [] },
  { id: 'gas', name: 'Gascony', kind: 'coastal', sc: false, home: null, coasts: [] },
  { id: 'gre', name: 'Greece', kind: 'coastal', sc: true, home: null, coasts: [] },
  { id: 'hel', name: 'Helgoland Bight', kind: 'sea', sc: false, home: null, coasts: [] },
  { id: 'hol', name: 'Holland', kind: 'coastal', sc: true, home: null, coasts: [] },
  { id: 'ion', name: 'Ionian Sea', kind: 'sea', sc: false, home: null, coasts: [] },
  { id: 'iri', name: 'Irish Sea', kind: 'sea', sc: false, home: null, coasts: [] },
  { id: 'kie', name: 'Kiel', kind: 'coastal', sc: true, home: 'germany', coasts: [] },
  { id: 'lon', name: 'London', kind: 'coastal', sc: true, home: 'england', coasts: [] },
  { id: 'lvn', name: 'Livonia', kind: 'coastal', sc: false, home: null, coasts: [] },
  { id: 'lvp', name: 'Liverpool', kind: 'coastal', sc: true, home: 'england', coasts: [] },
  { id: 'lyo', name: 'Gulf of Lyon', kind: 'sea', sc: false, home: null, coasts: [] },
  { id: 'mao', name: 'Mid-Atlantic Ocean', kind: 'sea', sc: false, home: null, coasts: [] },
  { id: 'mar', name: 'Marseilles', kind: 'coastal', sc: true, home: 'france', coasts: [] },
  { id: 'mos', name: 'Moscow', kind: 'inland', sc: true, home: 'russia', coasts: [] },
  { id: 'mun', name: 'Munich', kind: 'inland', sc: true, home: 'germany', coasts: [] },
  { id: 'naf', name: 'North Africa', kind: 'coastal', sc: false, home: null, coasts: [] },
  { id: 'nao', name: 'North Atlantic Ocean', kind: 'sea', sc: false, home: null, coasts: [] },
  { id: 'nap', name: 'Naples', kind: 'coastal', sc: true, home: 'italy', coasts: [] },
  { id: 'nth', name: 'North Sea', kind: 'sea', sc: false, home: null, coasts: [] },
  { id: 'nwg', name: 'Norwegian Sea', kind: 'sea', sc: false, home: null, coasts: [] },
  { id: 'nwy', name: 'Norway', kind: 'coastal', sc: true, home: null, coasts: [] },
  { id: 'par', name: 'Paris', kind: 'inland', sc: true, home: 'france', coasts: [] },
  { id: 'pic', name: 'Picardy', kind: 'coastal', sc: false, home: null, coasts: [] },
  { id: 'pie', name: 'Piedmont', kind: 'coastal', sc: false, home: null, coasts: [] },
  { id: 'por', name: 'Portugal', kind: 'coastal', sc: true, home: null, coasts: [] },
  { id: 'pru', name: 'Prussia', kind: 'coastal', sc: false, home: null, coasts: [] },
  { id: 'rom', name: 'Rome', kind: 'coastal', sc: true, home: 'italy', coasts: [] },
  { id: 'ruh', name: 'Ruhr', kind: 'inland', sc: false, home: null, coasts: [] },
  { id: 'rum', name: 'Rumania', kind: 'coastal', sc: true, home: null, coasts: [] },
  { id: 'ser', name: 'Serbia', kind: 'inland', sc: true, home: null, coasts: [] },
  { id: 'sev', name: 'Sevastopol', kind: 'coastal', sc: true, home: 'russia', coasts: [] },
  { id: 'sil', name: 'Silesia', kind: 'inland', sc: false, home: null, coasts: [] },
  { id: 'ska', name: 'Skagerrak', kind: 'sea', sc: false, home: null, coasts: [] },
  { id: 'smy', name: 'Smyrna', kind: 'coastal', sc: true, home: 'turkey', coasts: [] },
  { id: 'spa', name: 'Spain', kind: 'coastal', sc: true, home: null, coasts: ['nc', 'sc'] },
  { id: 'stp', name: 'St Petersburg', kind: 'coastal', sc: true, home: 'russia', coasts: ['nc', 'sc'] },
  { id: 'swe', name: 'Sweden', kind: 'coastal', sc: true, home: null, coasts: [] },
  { id: 'syr', name: 'Syria', kind: 'coastal', sc: false, home: null, coasts: [] },
  { id: 'tri', name: 'Trieste', kind: 'coastal', sc: true, home: 'austria', coasts: [] },
  { id: 'tun', name: 'Tunis', kind: 'coastal', sc: true, home: null, coasts: [] },
  { id: 'tus', name: 'Tuscany', kind: 'coastal', sc: false, home: null, coasts: [] },
  { id: 'tyr', name: 'Tyrolia', kind: 'inland', sc: false, home: null, coasts: [] },
  { id: 'tys', name: 'Tyrrhenian Sea', kind: 'sea', sc: false, home: null, coasts: [] },
  { id: 'ukr', name: 'Ukraine', kind: 'inland', sc: false, home: null, coasts: [] },
  { id: 'ven', name: 'Venice', kind: 'coastal', sc: true, home: 'italy', coasts: [] },
  { id: 'vie', name: 'Vienna', kind: 'inland', sc: true, home: 'austria', coasts: [] },
  { id: 'wal', name: 'Wales', kind: 'coastal', sc: false, home: null, coasts: [] },
  { id: 'war', name: 'Warsaw', kind: 'inland', sc: true, home: 'russia', coasts: [] },
  { id: 'wes', name: 'Western Mediterranean', kind: 'sea', sc: false, home: null, coasts: [] },
  { id: 'yor', name: 'Yorkshire', kind: 'coastal', sc: false, home: null, coasts: [] },
];

/** Army adjacency: land (inland/coastal) province pairs, each once, a < b. */
export const ARMY_EDGES: readonly (readonly [ProvinceId, ProvinceId])[] = [
  ['alb', 'gre'],
  ['alb', 'ser'],
  ['alb', 'tri'],
  ['ank', 'arm'],
  ['ank', 'con'],
  ['ank', 'smy'],
  ['apu', 'nap'],
  ['apu', 'rom'],
  ['apu', 'ven'],
  ['arm', 'sev'],
  ['arm', 'smy'],
  ['arm', 'syr'],
  ['bel', 'bur'],
  ['bel', 'hol'],
  ['bel', 'pic'],
  ['bel', 'ruh'],
  ['ber', 'kie'],
  ['ber', 'mun'],
  ['ber', 'pru'],
  ['ber', 'sil'],
  ['boh', 'gal'],
  ['boh', 'mun'],
  ['boh', 'sil'],
  ['boh', 'tyr'],
  ['boh', 'vie'],
  ['bre', 'gas'],
  ['bre', 'par'],
  ['bre', 'pic'],
  ['bud', 'gal'],
  ['bud', 'rum'],
  ['bud', 'ser'],
  ['bud', 'tri'],
  ['bud', 'vie'],
  ['bul', 'con'],
  ['bul', 'gre'],
  ['bul', 'rum'],
  ['bul', 'ser'],
  ['bur', 'gas'],
  ['bur', 'mar'],
  ['bur', 'mun'],
  ['bur', 'par'],
  ['bur', 'pic'],
  ['bur', 'ruh'],
  ['cly', 'edi'],
  ['cly', 'lvp'],
  ['con', 'smy'],
  ['den', 'kie'],
  ['den', 'swe'],
  ['edi', 'lvp'],
  ['edi', 'yor'],
  ['fin', 'nwy'],
  ['fin', 'stp'],
  ['fin', 'swe'],
  ['gal', 'rum'],
  ['gal', 'sil'],
  ['gal', 'ukr'],
  ['gal', 'vie'],
  ['gal', 'war'],
  ['gas', 'mar'],
  ['gas', 'par'],
  ['gas', 'spa'],
  ['gre', 'ser'],
  ['hol', 'kie'],
  ['hol', 'ruh'],
  ['kie', 'mun'],
  ['kie', 'ruh'],
  ['lon', 'wal'],
  ['lon', 'yor'],
  ['lvn', 'mos'],
  ['lvn', 'pru'],
  ['lvn', 'stp'],
  ['lvn', 'war'],
  ['lvp', 'wal'],
  ['lvp', 'yor'],
  ['mar', 'pie'],
  ['mar', 'spa'],
  ['mos', 'sev'],
  ['mos', 'stp'],
  ['mos', 'ukr'],
  ['mos', 'war'],
  ['mun', 'ruh'],
  ['mun', 'sil'],
  ['mun', 'tyr'],
  ['naf', 'tun'],
  ['nap', 'rom'],
  ['nwy', 'stp'],
  ['nwy', 'swe'],
  ['par', 'pic'],
  ['pie', 'tus'],
  ['pie', 'tyr'],
  ['pie', 'ven'],
  ['por', 'spa'],
  ['pru', 'sil'],
  ['pru', 'war'],
  ['rom', 'tus'],
  ['rom', 'ven'],
  ['rum', 'ser'],
  ['rum', 'sev'],
  ['rum', 'ukr'],
  ['ser', 'tri'],
  ['sev', 'ukr'],
  ['sil', 'war'],
  ['smy', 'syr'],
  ['tri', 'tyr'],
  ['tri', 'ven'],
  ['tri', 'vie'],
  ['tus', 'ven'],
  ['tyr', 'ven'],
  ['tyr', 'vie'],
  ['ukr', 'war'],
  ['wal', 'yor'],
];

/** Fleet adjacency: fleet-occupiable node pairs (split coasts as `spa/nc` etc.), each once, a < b. */
export const FLEET_EDGES: readonly (readonly [NodeId, NodeId])[] = [
  ['adr', 'alb'],
  ['adr', 'apu'],
  ['adr', 'ion'],
  ['adr', 'tri'],
  ['adr', 'ven'],
  ['aeg', 'bul/sc'],
  ['aeg', 'con'],
  ['aeg', 'eas'],
  ['aeg', 'gre'],
  ['aeg', 'ion'],
  ['aeg', 'smy'],
  ['alb', 'gre'],
  ['alb', 'ion'],
  ['alb', 'tri'],
  ['ank', 'arm'],
  ['ank', 'bla'],
  ['ank', 'con'],
  ['apu', 'ion'],
  ['apu', 'nap'],
  ['apu', 'ven'],
  ['arm', 'bla'],
  ['arm', 'sev'],
  ['bal', 'ber'],
  ['bal', 'bot'],
  ['bal', 'den'],
  ['bal', 'kie'],
  ['bal', 'lvn'],
  ['bal', 'pru'],
  ['bal', 'swe'],
  ['bar', 'nwg'],
  ['bar', 'nwy'],
  ['bar', 'stp/nc'],
  ['bel', 'eng'],
  ['bel', 'hol'],
  ['bel', 'nth'],
  ['bel', 'pic'],
  ['ber', 'kie'],
  ['ber', 'pru'],
  ['bla', 'bul/ec'],
  ['bla', 'con'],
  ['bla', 'rum'],
  ['bla', 'sev'],
  ['bot', 'fin'],
  ['bot', 'lvn'],
  ['bot', 'stp/sc'],
  ['bot', 'swe'],
  ['bre', 'eng'],
  ['bre', 'gas'],
  ['bre', 'mao'],
  ['bre', 'pic'],
  ['bul/ec', 'con'],
  ['bul/ec', 'rum'],
  ['bul/sc', 'con'],
  ['bul/sc', 'gre'],
  ['cly', 'edi'],
  ['cly', 'lvp'],
  ['cly', 'nao'],
  ['cly', 'nwg'],
  ['con', 'smy'],
  ['den', 'hel'],
  ['den', 'kie'],
  ['den', 'nth'],
  ['den', 'ska'],
  ['den', 'swe'],
  ['eas', 'ion'],
  ['eas', 'smy'],
  ['eas', 'syr'],
  ['edi', 'nth'],
  ['edi', 'nwg'],
  ['edi', 'yor'],
  ['eng', 'iri'],
  ['eng', 'lon'],
  ['eng', 'mao'],
  ['eng', 'nth'],
  ['eng', 'pic'],
  ['eng', 'wal'],
  ['fin', 'stp/sc'],
  ['fin', 'swe'],
  ['gas', 'mao'],
  ['gas', 'spa/nc'],
  ['gre', 'ion'],
  ['hel', 'hol'],
  ['hel', 'kie'],
  ['hel', 'nth'],
  ['hol', 'kie'],
  ['hol', 'nth'],
  ['ion', 'nap'],
  ['ion', 'tun'],
  ['ion', 'tys'],
  ['iri', 'lvp'],
  ['iri', 'mao'],
  ['iri', 'nao'],
  ['iri', 'wal'],
  ['lon', 'nth'],
  ['lon', 'wal'],
  ['lon', 'yor'],
  ['lvn', 'pru'],
  ['lvn', 'stp/sc'],
  ['lvp', 'nao'],
  ['lvp', 'wal'],
  ['lyo', 'mar'],
  ['lyo', 'pie'],
  ['lyo', 'spa/sc'],
  ['lyo', 'tus'],
  ['lyo', 'tys'],
  ['lyo', 'wes'],
  ['mao', 'naf'],
  ['mao', 'nao'],
  ['mao', 'por'],
  ['mao', 'spa/nc'],
  ['mao', 'spa/sc'],
  ['mao', 'wes'],
  ['mar', 'pie'],
  ['mar', 'spa/sc'],
  ['naf', 'tun'],
  ['naf', 'wes'],
  ['nao', 'nwg'],
  ['nap', 'rom'],
  ['nap', 'tys'],
  ['nth', 'nwg'],
  ['nth', 'nwy'],
  ['nth', 'ska'],
  ['nth', 'yor'],
  ['nwg', 'nwy'],
  ['nwy', 'ska'],
  ['nwy', 'stp/nc'],
  ['nwy', 'swe'],
  ['pie', 'tus'],
  ['por', 'spa/nc'],
  ['por', 'spa/sc'],
  ['rom', 'tus'],
  ['rom', 'tys'],
  ['rum', 'sev'],
  ['ska', 'swe'],
  ['smy', 'syr'],
  ['spa/sc', 'wes'],
  ['tri', 'ven'],
  ['tun', 'tys'],
  ['tun', 'wes'],
  ['tus', 'tys'],
  ['tys', 'wes'],
];
